// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-xJIzBc7qNrGWxWkNTYauvRisytXTa5k',
    appId: '1:1042927454817:web:4e62b2e53736e546ebb820',
    messagingSenderId: '1042927454817',
    projectId: 'todo-app-7cd39',
    authDomain: 'todo-app-7cd39.firebaseapp.com',
    storageBucket: 'todo-app-7cd39.appspot.com',
    measurementId: 'G-86BFTW23RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0s9hRZ0JTLFkRX50tvR3nH5ta_nKBLqk',
    appId: '1:1042927454817:android:23560e65319ce512ebb820',
    messagingSenderId: '1042927454817',
    projectId: 'todo-app-7cd39',
    storageBucket: 'todo-app-7cd39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgaOmeX2BHH_zY7udhpnan4R2s2SSWqUo',
    appId: '1:1042927454817:ios:b05d10612ba4dd37ebb820',
    messagingSenderId: '1042927454817',
    projectId: 'todo-app-7cd39',
    storageBucket: 'todo-app-7cd39.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgaOmeX2BHH_zY7udhpnan4R2s2SSWqUo',
    appId: '1:1042927454817:ios:b6feb2be8fb097cfebb820',
    messagingSenderId: '1042927454817',
    projectId: 'todo-app-7cd39',
    storageBucket: 'todo-app-7cd39.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
